<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RootNamespace>KUKULCAN.SharedKernel.Database</RootNamespace>
        <AssemblyName>KUKULCAN.SharedKernel.Database</AssemblyName>
        <SolutionDir>$(MSBuildThisFileDirectory)</SolutionDir>
        <BaseOutputPath>$(SolutionDir)Bin\$(MSBuildProjectName)\</BaseOutputPath>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="KUKULCAN.SharedKernel.Database.Tests" />
        <InternalsVisibleTo Include="KUKULCAN.SharedKernel.Database.PostgreSQL.Integration" />
        <InternalsVisibleTo Include="KUKULCAN.SharedKernel.Database.SQLServer.Integration" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="KUKULCAN.SharedKernel" Version="1.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.*" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="KUKULCAN.SharedKernel.Database.csproj~" />
    </ItemGroup>

    <!--
        DATABASE PROVIDER packages are NOT referenced here.
        Add them in each module's Infrastructure project or in the host application.

        SQL Server  : Microsoft.EntityFrameworkCore.SqlServer
        PostgreSQL  : Npgsql.EntityFrameworkCore.PostgreSQL
        MySQL       : MySql.EntityFrameworkCore
    -->

</Project>
